const latestUrl='./public/data/latest.json';const saldosUrl='./public/data/saldos-history.json';const $=s=>document.querySelector(s);const fmt=new Intl.NumberFormat('es-BO');let latest=null,currentFilter='all',saldosRecords=null;
const stateLabel=s=>({CRITICO:'CRÍTICO',ESCASEZ:'ESCASEZ',NORMAL:'NORMAL',ABUNDANCIA:'ABUNDANCIA',SATURADO:'SATURADO'})[s]||s||'—';
function localDateString(date=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/La_Paz',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),x=Object.fromEntries(p.map(v=>[v.type,v.value]));return `${x.year}-${x.month}-${x.day}`}
async function getJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderGlobal(d){const g=d.global,s=Math.max(0,Math.min(100,Number(g.score||0)));$('#globalScore').textContent=Math.round(s);$('#globalState').textContent=stateLabel(g.state);$('#gaugeFill').style.width=`${s}%`;$('#totalLiters').textContent=`${fmt.format(g.totalLiters||0)} L`;$('#availableStations').textContent=g.stationsAvailable??0;$('#totalStations').textContent=g.stationsTotal??d.stations?.length??0;const dt=new Date(d.scrapedAt);$('#updatedAt').textContent=Number.isNaN(dt.getTime())?'Actualización reciente':`Actualizado ${new Intl.DateTimeFormat('es-BO',{dateStyle:'short',timeStyle:'short'}).format(dt)}`}
function stationCard(s){return `<article class="card station state-${s.state}" data-key="${esc(s.key)}"><div class="station-top"><div><h3>${esc(s.name)}</h3><div class="address">${esc(s.address||'Dirección no disponible')}</div></div><div class="station-score">${Math.round(s.score??0)} · ${stateLabel(s.state)}</div></div><div class="station-main"><strong>${fmt.format(s.liters||0)}</strong><span>litros</span></div><div class="meter"><div style="width:${Math.max(0,Math.min(100,s.score||0))}%"></div></div><div class="station-meta"><span>${s.visibleInSource===false?'No aparece en BioCloud':`${fmt.format(s.vehiclesEstimated||0)} vehículos aprox.`}</span><span>${s.queueMinutes?`${s.queueMinutes} min/fila`:'—'}</span></div></article>`}
function renderStations(){const all=[...(latest?.stations||[])].sort((a,b)=>(b.liters||0)-(a.liters||0)),v=all.filter(s=>currentFilter==='available'?(s.liters||0)>0:currentFilter==='critical'?(s.liters||0)===0:true);$('#stationsGrid').innerHTML=v.length?v.map(stationCard).join(''):'<div class="empty">No hay surtidores para este filtro.</div>'}
function svgLineChart(svg,values,{min,max}={}){if(values.length<2){svg.innerHTML='<text x="50%" y="50%" text-anchor="middle" fill="#6f6a7d" font-size="13" font-family="ui-monospace,monospace">Aún no hay suficiente histórico</text>';return false}const w=600,h=220,p=14,lo=min??Math.min(...values),hi=max??Math.max(...values),span=(hi-lo)||1,pts=values.map((v,i)=>[p+i*((w-p*2)/(values.length-1)),h-p-((v-lo)/span)*(h-p*2)]),d=pts.map((pt,i)=>`${i?'L':'M'}${pt[0].toFixed(1)},${pt[1].toFixed(1)}`).join(' '),last=pts.at(-1);svg.innerHTML=`<line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" stroke="#322e3a" stroke-width="1"></line><path d="${d}" fill="none" stroke="#8b7cd8" stroke-width="2" vector-effect="non-scaling-stroke"></path><circle cx="${last[0]}" cy="${last[1]}" r="3" fill="#8b7cd8"></circle>`;return true}
function renderTrend(history){const rows=(history?.snapshots||[]).slice(-48),scores=rows.map(x=>Math.max(0,Math.min(100,Number(x.global?.score||0))));if(!svgLineChart($('#trendChart'),scores,{min:0,max:100})){$('#trendDelta').textContent='—';return}const delta=scores.at(-1)-scores[0];$('#trendDelta').textContent=`${delta>=0?'+':''}${delta.toFixed(1)} pts`}
async function getSaldosRecords(){if(saldosRecords)return saldosRecords;try{saldosRecords=(await getJSON(saldosUrl)).records||[]}catch{saldosRecords=[]}return saldosRecords}
async function openStationDialog(key){const station=(latest?.stations||[]).find(s=>s.key===key);if(!station)return;$('#dialogName').textContent=station.name;$('#dialogAddress').textContent=station.address||'Dirección no disponible';$('#dialogLiters').textContent=`${fmt.format(station.liters||0)} L`;$('#dialogMin').textContent='—';$('#dialogMax').textContent='—';$('#stationChart').innerHTML='';$('#stationDialog').showModal();const records=(await getSaldosRecords()).filter(r=>r.station===key).sort((a,b)=>new Date(a.scrapedAt)-new Date(b.scrapedAt));const liters=records.map(r=>Number(r.liters||0));if(liters.length){$('#dialogMin').textContent=`${fmt.format(Math.min(...liters))} L`;$('#dialogMax').textContent=`${fmt.format(Math.max(...liters))} L`}svgLineChart($('#stationChart'),liters)}
async function init(){try{latest=await getJSON(latestUrl);renderGlobal(latest);renderStations();try{renderTrend(await getJSON(`./public/data/history/${localDateString()}.json`))}catch{renderTrend(null)}}catch(e){console.error(e);$('#updatedAt').textContent='No se pudieron cargar los datos';$('#liveDot').style.background='#e2807a';$('#stationsGrid').innerHTML='<div class="empty">No se encontró public/data/latest.json. El dashboard funcionará cuando n8n publique el primer snapshot.</div>'}}
document.addEventListener('click',e=>{const b=e.target.closest('.filter');if(b){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;renderStations();return}const card=e.target.closest('.station[data-key]');if(card)openStationDialog(card.dataset.key)});
$('#dialogClose').addEventListener('click',()=>$('#stationDialog').close());
$('#stationDialog').addEventListener('click',e=>{if(e.target===$('#stationDialog'))$('#stationDialog').close()});
init();
