const latestUrl='./public/data/latest.json';const $=s=>document.querySelector(s);const fmt=new Intl.NumberFormat('es-BO');let latest=null,currentFilter='all',saldosRecords=null,dialogRecords=[],currentDialogStation=null,currentRange='5h';
const SALDOS_DAYS_BACK=2;
const STATION_CHART_HOURS=5;
const rangeHours={'5h':5,'10h':10,'1d':24};
const stateLabel=s=>({CRITICO:'CRÍTICO',ESCASEZ:'ESCASEZ',NORMAL:'NORMAL',ABUNDANCIA:'ABUNDANCIA',SATURADO:'SATURADO'})[s]||s||'—';
function localDateString(date=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/La_Paz',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),x=Object.fromEntries(p.map(v=>[v.type,v.value]));return `${x.year}-${x.month}-${x.day}`}
function dateOffsetString(daysAgo){return localDateString(new Date(Date.now()-daysAgo*86400000))}
async function getJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}

const rootStyle=getComputedStyle(document.documentElement);
const STATE_ORDER=['CRITICO','ESCASEZ','NORMAL','ABUNDANCIA','SATURADO'];
const STATE_COLORS=Object.fromEntries(STATE_ORDER.map(s=>[s,rootStyle.getPropertyValue(`--s-${s.toLowerCase()}`).trim()]));
const PANEL_COLOR=rootStyle.getPropertyValue('--panel').trim();
const VOLUME_COLOR=rootStyle.getPropertyValue('--volume').trim();
const VOLUME_IN_COLOR=rootStyle.getPropertyValue('--volume-in').trim();
const VOLUME_OUT_COLOR=rootStyle.getPropertyValue('--volume-out').trim();
const BALANCE_COLOR=rootStyle.getPropertyValue('--balance-line').trim();
function compactLiters(v){const n=Number(v)||0;if(n>=1000)return `${(n/1000).toFixed(n>=10000?0:1)}K L`;return `${Math.round(n)} L`}
const clampScore=v=>Math.max(0,Math.min(100,Number(v)||0));
const scoreToState=v=>STATE_ORDER[Math.min(4,Math.floor(clampScore(v)/20))];
const scoreColor=v=>STATE_COLORS[scoreToState(v)];
function renderGauge(score){const s=clampScore(score),cx=100,cy=100,r=80,angle=(180-(s/100)*180)*Math.PI/180,mx=(cx+r*Math.cos(angle)).toFixed(1),my=(cy-r*Math.sin(angle)).toFixed(1);$('#gaugeSvg').innerHTML=`<defs><linearGradient id="gaugeGrad" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stop-color="${STATE_COLORS.CRITICO}"/><stop offset="25%" stop-color="${STATE_COLORS.ESCASEZ}"/><stop offset="50%" stop-color="${STATE_COLORS.NORMAL}"/><stop offset="75%" stop-color="${STATE_COLORS.ABUNDANCIA}"/><stop offset="100%" stop-color="${STATE_COLORS.SATURADO}"/></linearGradient></defs><path d="M ${cx-r} ${cy} A ${r} ${r} 0 0 1 ${cx+r} ${cy}" fill="none" stroke="url(#gaugeGrad)" stroke-width="14" stroke-linecap="round"/><circle cx="${mx}" cy="${my}" r="8" fill="${PANEL_COLOR}" stroke="#fff" stroke-width="3"/>`}
function renderGlobal(d){const g=d.global,s=clampScore(g.score);$('#globalScore').textContent=Math.round(s);renderGauge(s);const stateEl=$('#globalState');STATE_ORDER.forEach(st=>stateEl.classList.remove('state-'+st));stateEl.textContent=stateLabel(g.state);if(g.state)stateEl.classList.add('state-'+g.state);$('#totalLiters').textContent=`${fmt.format(g.totalLiters||0)} L`;$('#availableStations').textContent=g.stationsAvailable??0;$('#totalStations').textContent=g.stationsTotal??d.stations?.length??0;const dt=new Date(d.scrapedAt);$('#updatedAt').textContent=Number.isNaN(dt.getTime())?'Actualización reciente':`Actualizado ${new Intl.DateTimeFormat('es-BO',{dateStyle:'short',timeStyle:'short'}).format(dt)}`}
function stationRecordsInRange(key,hours){const cutoff=Date.now()-hours*3600*1000;return (saldosRecords||[]).filter(r=>r.station===key&&new Date(r.scrapedAt).getTime()>=cutoff).sort((a,b)=>new Date(a.scrapedAt)-new Date(b.scrapedAt))}
function stationSparkline(key,color){const records=stationRecordsInRange(key,STATION_CHART_HOURS),liters=records.map(r=>Number(r.liters||0)),w=280,h=52,p=4;
if(liters.length<2)return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><text x="50%" y="50%" text-anchor="middle" dominant-baseline="middle" font-size="10" fill="#6f6a7d" font-family="'IBM Plex Mono',ui-monospace,monospace">Sin histórico de 5h</text></svg>`;
const lo=0,hi=Math.max(...liters),span=(hi-lo)||1,pts=liters.map((v,i)=>[p+i*((w-p*2)/(liters.length-1)),h-p-((v-lo)/span)*(h-p*2)]),d=pts.map((pt,i)=>`${i?'L':'M'}${pt[0].toFixed(1)},${pt[1].toFixed(1)}`).join(' '),areaD=`${d} L${pts.at(-1)[0].toFixed(1)},${h-p} L${pts[0][0].toFixed(1)},${h-p} Z`,last=pts.at(-1);
return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><path d="${areaD}" fill="${color}" fill-opacity="0.14" stroke="none"></path><path d="${d}" fill="none" stroke="${color}" stroke-width="2" vector-effect="non-scaling-stroke"></path><circle cx="${last[0].toFixed(1)}" cy="${last[1].toFixed(1)}" r="3" fill="${color}"></circle></svg>`}
function stationConsumptionLabel(key){const records=stationRecordsInRange(key,1);if(records.length<2)return 'Sin datos (1h)';const first=Number(records[0].liters||0),last=Number(records.at(-1).liters||0),delta=last-first;if(delta>0)return `Recarga: +${fmt.format(delta)} L (1h)`;if(delta<0)return `~${fmt.format(Math.abs(delta))} L gastados (1h)`;return 'Sin cambios (1h)'}
function stationCard(s){const color=scoreColor(s.score);return `<article class="card station state-${s.state}" data-key="${esc(s.key)}"><div class="station-top"><div><h3>${esc(s.name)}</h3><div class="address">${esc(s.address||'Dirección no disponible')}</div></div><div class="station-score">${Math.round(s.score??0)} · ${stateLabel(s.state)}</div></div><div class="station-main"><strong>${fmt.format(s.liters||0)}</strong><span>litros</span></div><div class="station-chart">${stationSparkline(s.key,color)}</div><div class="station-meta"><span>${s.visibleInSource===false?'Sin saldo':`${fmt.format(s.vehiclesEstimated||0)} vehículos aprox.`}</span><span>${esc(stationConsumptionLabel(s.key))}</span></div></article>`}
function renderStations(){const all=[...(latest?.stations||[])].sort((a,b)=>(b.liters||0)-(a.liters||0)),v=all.filter(s=>currentFilter==='available'?(s.liters||0)>0:currentFilter==='critical'?(s.liters||0)===0:true);$('#stationsGrid').innerHTML=v.length?v.map(stationCard).join(''):'<div class="empty">No hay surtidores para este filtro.</div>'}
function svgLineChart(svg,values,{min,max,times,detailEl,formatValue,color='#8b7cd8'}={}){svg.onclick=null;svg.style.cursor='';if(values.length<2){svg.innerHTML='<text x="50%" y="50%" text-anchor="middle" fill="#6f6a7d" font-size="13" font-family="ui-monospace,monospace">Aún no hay suficiente histórico</text>';if(detailEl)detailEl.textContent='Aún no hay suficiente histórico para mostrar detalle.';return false}
const w=600,h=220,p=14,lo=min??Math.min(...values),hi=max??Math.max(...values),span=(hi-lo)||1,pts=values.map((v,i)=>[p+i*((w-p*2)/(values.length-1)),h-p-((v-lo)/span)*(h-p*2)]),d=pts.map((pt,i)=>`${i?'L':'M'}${pt[0].toFixed(1)},${pt[1].toFixed(1)}`).join(' '),areaD=`${d} L${pts.at(-1)[0].toFixed(1)},${h-p} L${pts[0][0].toFixed(1)},${h-p} Z`,last=pts.at(-1);
svg.innerHTML=`<path d="${areaD}" fill="${color}" fill-opacity="0.14" stroke="none"></path><line class="chart-guide" x1="${last[0]}" y1="${p}" x2="${last[0]}" y2="${h-p}" stroke="#f4b74e" stroke-width="1" stroke-dasharray="3,3" style="display:none"></line><path d="${d}" fill="none" stroke="${color}" stroke-width="2" vector-effect="non-scaling-stroke"></path><circle cx="${last[0]}" cy="${last[1]}" r="3" fill="${color}"></circle><circle class="chart-marker" r="5" fill="none" stroke="#f4b74e" stroke-width="2" style="display:none"></circle>`;
if(detailEl)detailEl.textContent='Toca el gráfico para ver el detalle de un momento.';
if(!times)return true;
const guide=svg.querySelector('.chart-guide'),marker=svg.querySelector('.chart-marker');
svg.style.cursor='pointer';
svg.onclick=evt=>{const rect=svg.getBoundingClientRect(),svgX=(evt.clientX-rect.left)*(w/rect.width),step=(w-p*2)/(values.length-1),idx=Math.max(0,Math.min(values.length-1,Math.round((svgX-p)/step))),pt=pts[idx];guide.setAttribute('x1',pt[0]);guide.setAttribute('x2',pt[0]);guide.style.display='';marker.setAttribute('cx',pt[0]);marker.setAttribute('cy',pt[1]);marker.style.display='';if(detailEl){const t=times[idx],timeLabel=t?new Intl.DateTimeFormat('es-BO',{dateStyle:'short',timeStyle:'short'}).format(new Date(t)):`Punto ${idx+1}`,valueLabel=formatValue?formatValue(values[idx]):values[idx];detailEl.textContent=`${timeLabel} · ${valueLabel}`}};
return true}
function drawZoneChart(svg,scores,times,detailEl,sold,liters){svg.onclick=null;svg.style.cursor='';
const w=Math.max(280,Math.round(svg.getBoundingClientRect().width))||600,h=Math.max(160,Math.round(svg.getBoundingClientRect().height))||220;
svg.setAttribute('viewBox',`0 0 ${w} ${h}`);
if(scores.length<2){svg.innerHTML=`<text x="${w/2}" y="${h/2}" text-anchor="middle" fill="#6f6a7d" font-size="13" font-family="ui-monospace,monospace">Aún no hay suficiente histórico</text>`;if(detailEl)detailEl.textContent='Aún no hay suficiente histórico para mostrar detalle.';return}
const p=14,plotW=w-p*2,plotH=h-p*2,bandH=plotH/5;
const pts=scores.map((v,i)=>[p+i*(plotW/(scores.length-1)),h-p-(clampScore(v)/100)*plotH]);
const parts=[];
for(let i=0;i<5;i++){const y=p+i*bandH,state=STATE_ORDER[4-i],color=STATE_COLORS[state];parts.push(`<rect x="${p}" y="${y.toFixed(1)}" width="${plotW}" height="${bandH.toFixed(1)}" fill="${color}" fill-opacity="${i===0?0.16:0.07}"></rect>`);if(i>0)parts.push(`<line x1="${p}" y1="${y.toFixed(1)}" x2="${w-p}" y2="${y.toFixed(1)}" stroke="#322e3a" stroke-width="1" stroke-dasharray="2,4"></line>`);parts.push(`<text x="${w-p-6}" y="${(y+bandH/2+3).toFixed(1)}" text-anchor="end" font-size="9" font-family="'IBM Plex Mono',ui-monospace,monospace" fill="${color}" opacity="0.85">${stateLabel(state)}</text>`)}
const hasBalance=Array.isArray(liters)&&liters.length===scores.length;
if(hasBalance){const minL=Math.min(...liters),maxL=Math.max(...liters),spanL=(maxL-minL)||1,balPts=liters.map((v,i)=>[pts[i][0],h-p-((v-minL)/spanL)*plotH]),balD=balPts.map((pt,i)=>`${i?'L':'M'}${pt[0].toFixed(1)},${pt[1].toFixed(1)}`).join(' '),lastBal=balPts.at(-1);
parts.push(`<path d="${balD}" fill="none" stroke="${BALANCE_COLOR}" stroke-width="1.5" stroke-opacity="0.55" stroke-linecap="round" vector-effect="non-scaling-stroke"></path>`);
parts.push(`<circle cx="${lastBal[0].toFixed(1)}" cy="${lastBal[1].toFixed(1)}" r="3" fill="${BALANCE_COLOR}"></circle>`)}
const hasVolume=Array.isArray(sold)&&sold.length===scores.length;
if(hasVolume){const volFrac=0.26,maxAbs=Math.max(1,...sold.map(v=>Math.abs(v))),barBaseY=h-p,barZoneH=volFrac*plotH,zeroY=barBaseY-barZoneH/2,halfH=barZoneH/2,barW=Math.max(1,(plotW/(scores.length-1))*0.92);
sold.forEach((v,i)=>{const bh=(Math.abs(v)/maxAbs)*halfH;if(bh<=0)return;const x=pts[i][0]-barW/2,y=v>=0?zeroY-bh:zeroY,color=v>=0?VOLUME_IN_COLOR:VOLUME_OUT_COLOR;parts.push(`<rect x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${barW.toFixed(1)}" height="${bh.toFixed(1)}" fill="${color}" fill-opacity="0.55"></rect>`)});
parts.push(`<line x1="${p}" y1="${zeroY.toFixed(1)}" x2="${w-p}" y2="${zeroY.toFixed(1)}" stroke="${VOLUME_COLOR}" stroke-width="1" stroke-opacity="0.4"></line>`);
parts.push(`<text x="${(p+3).toFixed(1)}" y="${(zeroY-halfH+9).toFixed(1)}" text-anchor="start" font-size="8" font-family="'IBM Plex Mono',ui-monospace,monospace" fill="${VOLUME_IN_COLOR}" opacity="0.85">+${compactLiters(maxAbs)}</text>`);
parts.push(`<text x="${(p+3).toFixed(1)}" y="${(zeroY+3).toFixed(1)}" text-anchor="start" font-size="8" font-family="'IBM Plex Mono',ui-monospace,monospace" fill="${VOLUME_COLOR}" opacity="0.75">0 L</text>`);
parts.push(`<text x="${(p+3).toFixed(1)}" y="${(zeroY+halfH-2).toFixed(1)}" text-anchor="start" font-size="8" font-family="'IBM Plex Mono',ui-monospace,monospace" fill="${VOLUME_OUT_COLOR}" opacity="0.85">-${compactLiters(maxAbs)}</text>`)}
const tickCount=Math.min(5,times.length);
for(let i=0;i<tickCount;i++){const idx=Math.round(i*(times.length-1)/(tickCount-1||1)),x=pts[idx][0],label=times[idx]?new Intl.DateTimeFormat('es-BO',{day:'2-digit',month:'short'}).format(new Date(times[idx])):'',anchor=i===0?'start':i===tickCount-1?'end':'middle';parts.push(`<text x="${x.toFixed(1)}" y="${h-2}" text-anchor="${anchor}" font-size="9" font-family="'IBM Plex Mono',ui-monospace,monospace" fill="#6f6a7d">${esc(label)}</text>`)}
for(let i=1;i<pts.length;i++){const color=scoreColor((scores[i-1]+scores[i])/2);parts.push(`<path d="M${pts[i-1][0].toFixed(1)},${pts[i-1][1].toFixed(1)} L${pts[i][0].toFixed(1)},${pts[i][1].toFixed(1)}" fill="none" stroke="${color}" stroke-width="2" stroke-linecap="round" vector-effect="non-scaling-stroke"></path>`)}
const last=pts.at(-1),lastColor=scoreColor(scores.at(-1));
parts.push(`<line class="chart-guide" x1="${last[0].toFixed(1)}" y1="${p}" x2="${last[0].toFixed(1)}" y2="${h-p}" stroke="#f4b74e" stroke-width="1" stroke-dasharray="3,3" style="display:none"></line>`);
parts.push(`<circle cx="${last[0].toFixed(1)}" cy="${last[1].toFixed(1)}" r="4" fill="${lastColor}" stroke="${PANEL_COLOR}" stroke-width="2"></circle>`);
parts.push(`<circle class="chart-marker" r="5" fill="none" stroke="#f4b74e" stroke-width="2" style="display:none"></circle>`);
parts.push(`<rect x="${(last[0]-16).toFixed(1)}" y="${(last[1]-24).toFixed(1)}" width="32" height="18" rx="4" fill="${lastColor}"></rect>`);
parts.push(`<text x="${last[0].toFixed(1)}" y="${(last[1]-11).toFixed(1)}" text-anchor="middle" font-size="11" font-weight="700" font-family="'IBM Plex Mono',ui-monospace,monospace" fill="${PANEL_COLOR}">${Math.round(scores.at(-1))}</text>`);
svg.innerHTML=parts.join('');
if(detailEl)detailEl.textContent='Toca el gráfico para ver el detalle de un momento.';
const guide=svg.querySelector('.chart-guide'),marker=svg.querySelector('.chart-marker');
svg.style.cursor='pointer';
svg.onclick=evt=>{const rect=svg.getBoundingClientRect(),svgX=(evt.clientX-rect.left)*(w/rect.width),step=plotW/(pts.length-1),idx=Math.max(0,Math.min(pts.length-1,Math.round((svgX-p)/step))),pt=pts[idx];guide.setAttribute('x1',pt[0]);guide.setAttribute('x2',pt[0]);guide.style.display='';marker.setAttribute('cx',pt[0]);marker.setAttribute('cy',pt[1]);marker.setAttribute('stroke',scoreColor(scores[idx]));marker.style.display='';if(detailEl){const t=times[idx],timeLabel=t?new Intl.DateTimeFormat('es-BO',{dateStyle:'short',timeStyle:'short'}).format(new Date(t)):`Punto ${idx+1}`,volLabel=hasVolume?(sold[idx]>0?` · +${fmt.format(Math.round(sold[idx]))} L ingresados`:sold[idx]<0?` · ${fmt.format(Math.round(Math.abs(sold[idx])))} L vendidos`:' · Sin cambio de stock'):'',balLabel=hasBalance?` · Saldo: ${fmt.format(Math.round(liters[idx]))} L`:'';detailEl.textContent=`${timeLabel} · ${Math.round(scores[idx])}/100 · ${stateLabel(scoreToState(scores[idx]))}${balLabel}${volLabel}`}}}
function downsample(scores,times,max){if(scores.length<=max)return{scores,times};const stride=Math.ceil(scores.length/max),outS=[],outT=[];for(let i=0;i<scores.length;i+=stride){outS.push(scores[i]);outT.push(times[i])}if(outT.at(-1)!==times.at(-1)){outS.push(scores.at(-1));outT.push(times.at(-1))}return{scores:outS,times:outT}}
function downsampleWithVolume(scores,sold,liters,times,max){if(scores.length<=max)return{scores,sold,liters,times};const stride=Math.ceil(scores.length/max),outS=[],outV=[],outL=[],outT=[];for(let i=0;i<scores.length;i+=stride){const end=Math.min(i+stride,scores.length);outS.push(scores[i]);outT.push(times[i]);outL.push(liters[i]);let sum=0;for(let j=i;j<end;j++)sum+=sold[j];outV.push(sum)}if(outT.at(-1)!==times.at(-1)){outS.push(scores.at(-1));outT.push(times.at(-1));outV.push(sold.at(-1));outL.push(liters.at(-1))}return{scores:outS,sold:outV,liters:outL,times:outT}}
async function fetchHistoryDay(dateStr){try{return await getJSON(`./public/data/history/${dateStr}.json`)}catch{return null}}
async function loadHistoryRange(maxDays){const cap=Math.min(maxDays,400),missGrace=20;let hits=0,misses=0;const files=[];
for(let start=0;start<cap;start+=10){const batch=[];for(let i=start;i<Math.min(start+10,cap);i++)batch.push(i);const results=await Promise.all(batch.map(i=>fetchHistoryDay(dateOffsetString(i))));let batchHits=0;results.forEach(f=>{if(f){files.push(f);batchHits++;hits++}else misses++});if(batchHits===0&&((hits>0&&misses>=missGrace)||(hits===0&&misses>=missGrace)))break}
files.sort((a,b)=>new Date(a.date)-new Date(b.date));
const snapshots=files.flatMap(f=>f.snapshots||[]);
snapshots.sort((a,b)=>new Date(a.scrapedAt)-new Date(b.scrapedAt));
return snapshots}
const rangeCache={};
function getRangeSnapshots(maxDays,key){if(!rangeCache[key])rangeCache[key]=loadHistoryRange(maxDays);return rangeCache[key]}
async function renderTrendChart(rangeKey){const days=rangeKey==='7d'?7:rangeKey==='30d'?30:400;const snaps=await getRangeSnapshots(days,rangeKey);const points=snaps.map(s=>({score:clampScore(s.global?.score),liters:Number(s.global?.totalLiters||0),time:s.scrapedAt}));if(latest&&(!points.length||new Date(latest.scrapedAt)>new Date(points.at(-1).time)))points.push({score:clampScore(latest.global.score),liters:Number(latest.global.totalLiters||0),time:latest.scrapedAt});
const rawScores=points.map(p=>p.score),rawTimes=points.map(p=>p.time),rawLiters=points.map(p=>p.liters),rawDelta=rawLiters.map((v,i)=>i===0?0:v-rawLiters[i-1]);
const{scores,sold,liters,times}=downsampleWithVolume(rawScores,rawDelta,rawLiters,rawTimes,180);
drawZoneChart($('#trendChart'),scores,times,$('#trendChartDetail'),sold,liters);
if(scores.length<2){$('#trendDelta').textContent='—';return}const delta=scores.at(-1)-scores[0];$('#trendDelta').textContent=`${delta>=0?'+':''}${delta.toFixed(1)} pts`}
async function fetchSaldosDay(dateStr){try{return await getJSON(`./public/data/saldos/${dateStr}.json`)}catch{return null}}
async function getSaldosRecords(){if(saldosRecords)return saldosRecords;const days=await Promise.all(Array.from({length:SALDOS_DAYS_BACK},(_,i)=>fetchSaldosDay(dateOffsetString(i))));saldosRecords=days.filter(Boolean).flatMap(d=>d.records||[]);return saldosRecords}
function renderStationChart(){const hours=rangeHours[currentRange]??STATION_CHART_HOURS,cutoff=Date.now()-hours*3600*1000,records=dialogRecords.filter(r=>new Date(r.scrapedAt).getTime()>=cutoff),liters=records.map(r=>Number(r.liters||0)),times=records.map(r=>r.scrapedAt),color=currentDialogStation?scoreColor(currentDialogStation.score):'#8b7cd8';svgLineChart($('#stationChart'),liters,{min:0,times,detailEl:$('#stationChartDetail'),formatValue:v=>`${fmt.format(v)} L`,color})}
async function openStationDialog(key){const station=(latest?.stations||[]).find(s=>s.key===key);if(!station)return;currentDialogStation=station;currentRange='5h';document.querySelectorAll('.range-filters .filter').forEach(x=>x.classList.toggle('active',x.dataset.range==='5h'));$('#dialogName').textContent=station.name;$('#dialogAddress').textContent=station.address||'Dirección no disponible';$('#dialogLiters').textContent=`${fmt.format(station.liters||0)} L`;$('#stationChart').innerHTML='';dialogRecords=[];$('#stationDialog').showModal();dialogRecords=(await getSaldosRecords()).filter(r=>r.station===key).sort((a,b)=>new Date(a.scrapedAt)-new Date(b.scrapedAt));renderStationChart()}
async function init(){try{latest=await getJSON(latestUrl);renderGlobal(latest);await getSaldosRecords();renderStations();renderTrendChart('7d')}catch(e){console.error(e);$('#updatedAt').textContent='No se pudieron cargar los datos';$('#liveDot').style.background='#e2807a';$('#stationsGrid').innerHTML='<div class="empty">No se encontró public/data/latest.json. El dashboard funcionará cuando n8n publique el primer snapshot.</div>'}}
let currentChartRange='7d';
document.addEventListener('click',e=>{const cr=e.target.closest('#chartRangeButtons .filter');if(cr){document.querySelectorAll('#chartRangeButtons .filter').forEach(x=>x.classList.remove('active'));cr.classList.add('active');currentChartRange=cr.dataset.range;renderTrendChart(currentChartRange);return}const r=e.target.closest('.range-filters .filter');if(r){document.querySelectorAll('.range-filters .filter').forEach(x=>x.classList.remove('active'));r.classList.add('active');currentRange=r.dataset.range;renderStationChart();return}const b=e.target.closest('.filters:not(.range-filters) .filter');if(b){document.querySelectorAll('.filters:not(.range-filters) .filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;renderStations();return}const card=e.target.closest('.station[data-key]');if(card)openStationDialog(card.dataset.key)});
$('#dialogClose').addEventListener('click',()=>$('#stationDialog').close());
$('#stationDialog').addEventListener('click',e=>{if(e.target===$('#stationDialog'))$('#stationDialog').close()});
let chartResizeTimer=null;
window.addEventListener('resize',()=>{clearTimeout(chartResizeTimer);chartResizeTimer=setTimeout(()=>{if(latest)renderTrendChart(currentChartRange)},200)});
init();
