/**
 * Bundles src/index-engine/*.ts into a single, dependency-free CommonJS-style
 * script that an n8n Code node can `eval`/paste — no filesystem access, no
 * `require()` of external files, works regardless of how the n8n container
 * is provisioned. This is a mechanical transpile + concatenation, never a
 * hand-copy: the engine logic itself has exactly one source of truth
 * (src/index-engine), this just packages it for a runtime that can't import
 * local TS modules.
 *
 * Used by scripts/n8n/update-workflow.ts. Can also be run standalone:
 *   node scripts/n8n/build-engine-bundle.ts > /tmp/bundle.js
 */
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import ts from 'typescript';

const ENGINE_DIR = path.resolve(import.meta.dirname, '../../src/index-engine');

// Dependency order matters: each module may only `require()` modules earlier in this list.
const MODULE_ORDER = ['types', 'crises', 'fuel-level', 'baseline', 'flow', 'pressure', 'engine'];

function transpile(source: string): string {
  const result = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2019,
      esModuleInterop: true,
      importHelpers: false,
    },
  });
  return result.outputText;
}

/** Rewrites `require("./foo.ts")` (and `require("./foo.js")`) to `require("foo")` — a bare id resolved by our own tiny loader below, not Node's resolver. */
function normalizeRequireIds(code: string): string {
  return code.replace(/require\("\.\/([^"]+?)\.(?:ts|js)"\)/g, (_match, id: string) => `require("${id}")`);
}

export async function buildEngineBundle(): Promise<string> {
  const modules = await Promise.all(
    MODULE_ORDER.map(async (id) => {
      const source = await readFile(path.join(ENGINE_DIR, `${id}.ts`), 'utf8');
      const compiled = normalizeRequireIds(transpile(source));
      return { id, compiled };
    }),
  );

  const defineCalls = modules
    .map(
      ({ id, compiled }) => `__define(${JSON.stringify(id)}, function (module, exports, require) {\n${compiled}\n});`,
    )
    .join('\n\n');

  return [
    '// AUTO-GENERATED by scripts/n8n/build-engine-bundle.ts from src/index-engine/*.ts — DO NOT EDIT BY HAND.',
    '// Regenerate with: npm run build:n8n-workflow',
    'var GasolinaIndexEngine = (function () {',
    '  var __modules = {};',
    '  var __cache = {};',
    '  function __define(id, factory) { __modules[id] = factory; }',
    '  function __require(id) {',
    '    if (__cache[id]) return __cache[id].exports;',
    '    var mod = { exports: {} };',
    '    __cache[id] = mod;',
    '    __modules[id](mod, mod.exports, __require);',
    '    return mod.exports;',
    '  }',
    defineCalls,
    "  return __require('engine');",
    '})();',
  ].join('\n');
}

async function main() {
  process.stdout.write((await buildEngineBundle()) + '\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exitCode = 1;
  });
}
